export {default as Register} from './Register'
export {default as Login} from './Login'
export {default as Home} from './Home'
export {default as Detail} from './Detail'
export {default as Recommend} from './Recommend'
export {default as NotFound} from './NotFound'